apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dttzao2do-go 
  janus-idp.io/tekton: dttzao2do-go
  backstage.io/kubernetes-id: dttzao2do-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dttzao2do-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml